baseURL = 'https://nishanshetty.github.io/life-in-weeks/'
languageCode = 'en-us'
title = 'My Life in Weeks'
disableKinds = ["taxonomy", "taxonomy"]
enableEmoji = true


[params]
author = "Nishan Shetty"
